# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfd305b269d750dcee588ddde199e19d8692f63f19fc9aca6d81503d2e2f305babdda36579db89c2d4256d291accd242ed901187e267ff1b951992489704e79

test:
  secret_key_base: 096ffc277547d5f697ea34ec00e1190e45a442ea042790f190bad33fb3943f1d88c8692efd6e03e97898de2939fc75bc1eb399652f599f70fb4763b6a8a8b6b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
